Fix some packaging issues

diff --git a/tools/build/deb/nvidia-docker.prerm b/tools/build/deb/nvidia-docker.prerm
--- a/tools/build/deb/nvidia-docker.prerm
+++ b/tools/build/deb/nvidia-docker.prerm
@@ -7,9 +7,10 @@ NVIDIA_DOCKER_ROOT=/var/lib/nvidia-docker
 
 case "$1" in
     remove)
-        echo "Purging NVIDIA volumes ..."
-        docker volume ls | awk -v drv="$NVIDIA_DOCKER_DRIVER" '{if ($1 == drv) print $2}' | xargs -r docker volume rm
-        find "$NVIDIA_DOCKER_ROOT" ! -wholename "$NVIDIA_DOCKER_ROOT" -type d -empty -delete
+        echo "Purging NVIDIA volumes"
+        docker volume ls | awk -v drv="$NVIDIA_DOCKER_DRIVER" '{if ($1 == drv) print $2}' | xargs -r docker volume rm ||
+            echo "Failed to remove NVIDIA volumes, ignoring"
+        find "$NVIDIA_DOCKER_ROOT" ! -wholename "$NVIDIA_DOCKER_ROOT" -type d -empty -delete || true
     ;;
 
     upgrade|deconfigure|failed-upgrade)
